### ISSUE TITLE
Rails-specific values inside the middleware

### ISSUE THREAD

**Issue by halorgium** [heroku/sass_on_heroku#1]
Might pay to pass the RAILS_ROOT into the middleware in init.rb: 

```
ActionController::Dispatcher.middleware.use SassOnHeroku, RAILS_ROOT
```

Then in a normal rackup, it can be used: 

```
use SassOnHeroku, Dir.pwd
```

Maybe use Rack::File to serve the generated .css files?

**Comment by pedro** [comment]
Excellent idea! Thanks, I'll do it.
